# Generators are all non-empty subsets of {1,2,3,4}
# Naming: t1, t2, t3, t4, t12, t13, t14, t23, t24, t34, t123, t124, t134, t234, t1234
#
# Commutativity rule: t_K and t_J commute iff K subset of J, J subset of K, or K inter J = empty
# They do NOT commute when they "cross": partially overlap but neither contains the other.

F := FreeGroup("t1","t2","t3","t4","t12","t13","t14","t23","t24","t34","t123","t124","t134","t234","t1234");

t1    := F.1;
t2    := F.2;
t3    := F.3;
t4    := F.4;
t12   := F.5;
t13   := F.6;
t14   := F.7;
t23   := F.8;
t24   := F.9;
t34   := F.10;
t123  := F.11;
t124  := F.12;
t134  := F.13;
t234  := F.14;
t1234 := F.15;

AllGens := [t1,t2,t3,t4,t12,t13,t14,t23,t24,t34,t123,t124,t134,t234,t1234];

# Index sets for each generator
IndexSets := [
    [1],        # t1
    [2],        # t2
    [3],        # t3
    [4],        # t4
    [1,2],      # t12
    [1,3],      # t13
    [1,4],      # t14
    [2,3],      # t23
    [2,4],      # t24
    [3,4],      # t34
    [1,2,3],    # t123
    [1,2,4],    # t124
    [1,3,4],    # t134
    [2,3,4],    # t234
    [1,2,3,4]   # t1234
];

n := Length(AllGens);

# t_K and t_J commute iff K subset J, or J subset K, or K inter J = empty
DoCommute := function(K, J)
    if IsSubset(J, K) then return true; fi;
    if IsSubset(K, J) then return true; fi;
    if Length(Intersection(K, J)) = 0 then return true; fi;
    return false;
end;

# All generators are involutions
involutions := List([1..n], i -> AllGens[i]^2);

# Add commutativity relation only when the rule holds
commutators := [];
for i in [1..n] do
    for j in [i+1..n] do
        if DoCommute(IndexSets[i], IndexSets[j]) then
            Add(commutators, AllGens[i]*AllGens[j]*AllGens[i]^-1*AllGens[j]^-1);
        fi;
    od;
od;

Print("Number of commutativity relations: ", Length(commutators), "\n");

# Crossing pairs (those that do NOT commute) - for reference
Print("Non-commuting pairs (crossing index sets):\n");
for i in [1..n] do
    for j in [i+1..n] do
        if not DoCommute(IndexSets[i], IndexSets[j]) then
            Print("  ", IndexSets[i], " x ", IndexSets[j], "\n");
        fi;
    od;
od;

rels := Concatenation(involutions, commutators);

G := F / rels;

T1    := G.1;
T2    := G.2;
T3    := G.3;
T4    := G.4;
T12   := G.5;
T13   := G.6;
T14   := G.7;
T23   := G.8;
T24   := G.9;
T34   := G.10;
T123  := G.11;
T124  := G.12;
T134  := G.13;
T234  := G.14;
T1234 := G.15;

# Subgroup H generated by t_{K cup {4}} * t_K for all K subset of {1,2,3}
# K = {}:      t4            (t_empty = identity)
# K = {1}:     t14 * t1
# K = {2}:     t24 * t2
# K = {3}:     t34 * t3
# K = {1,2}:   t124 * t12
# K = {1,3}:   t134 * t13
# K = {2,3}:   t234 * t23
# K = {1,2,3}: t1234 * t123

gensH := [
    T4,
    T14 * T1,
    T24 * T2,
    T34 * T3,
    T124 * T12,
    T134 * T13,
    T234 * T23,
    T1234 * T123
];

# ---- Tits geometric (matrix) representation of G ----
# G is an infinite right-angled Coxeter group, so IsomorphismFpGroup(H)
# via coset enumeration diverges.  Use the faithful Tits representation
# instead: each generator s_i acts as the reflection
#   v -> v - 2*B(e_i, v)*e_i
# with bilinear form B(e_i,e_j) = 1 (i=j), 0 (commute), -1 (don't commute).

dim := Length(AllGens);

Bmat := NullMat(dim, dim);
for i in [1..dim] do
    for j in [1..dim] do
        if i = j then
            Bmat[i][j] := 1;
        elif DoCommute(IndexSets[i], IndexSets[j]) then
            Bmat[i][j] := 0;
        else
            Bmat[i][j] := -1;
        fi;
    od;
od;

# Reflection matrix for generator i: identity with row i replaced by
# delta_{ik} - 2*B_{ik}.  All entries are integers.
ReflMats := [];
for i in [1..dim] do
    M := IdentityMat(dim);
    for k in [1..dim] do
        M[i][k] := M[i][k] - 2*Bmat[i][k];
    od;
    Add(ReflMats, M);
od;

idMat := IdentityMat(dim);

# Verify involutions
for i in [1..dim] do
    if ReflMats[i]^2 <> idMat then
        Print("ERROR: ReflMats[", i, "] is not an involution\n");
    fi;
od;

# Matrix generators of H  (same order as gensH)
# [T4, T14*T1, T24*T2, T34*T3, T124*T12, T134*T13, T234*T23, T1234*T123]
#  idx: 4      7,1     9,2     10,3       12,5       13,6      14,8       15,11
gensH_mats := [
    ReflMats[4],
    ReflMats[7]  * ReflMats[1],
    ReflMats[9]  * ReflMats[2],
    ReflMats[10] * ReflMats[3],
    ReflMats[12] * ReflMats[5],
    ReflMats[13] * ReflMats[6],
    ReflMats[14] * ReflMats[8],
    ReflMats[15] * ReflMats[11]
];

gensH_names := ["T4", "T14*T1", "T24*T2", "T34*T3",
                "T124*T12", "T134*T13", "T234*T23", "T1234*T123"];

Print("\nPresentation of H (via Tits representation):\n");
Print("Generators (all involutions): ", gensH_names, "\n");

# Pairwise orders: since every generator has order 2, the presentation
# is determined by the orders m_{ij} of all products h_i * h_j.
# (Coxeter-type presentation: <h_i | h_i^2, (h_i h_j)^{m_{ij}}>)
maxCheck := 60;
Print("\nPairwise product orders (m_{ij}):\n");
for i in [1..Length(gensH_mats)] do
    for j in [i+1..Length(gensH_mats)] do
        prod := gensH_mats[i] * gensH_mats[j];
        cur  := prod;
        ord  := 1;
        while cur <> idMat and ord <= maxCheck do
            ord := ord + 1;
            cur := cur * prod;
        od;
        if cur = idMat then
            Print("  m(", gensH_names[i], ", ", gensH_names[j], ") = ", ord, "\n");
        else
            Print("  m(", gensH_names[i], ", ", gensH_names[j], ") > ", maxCheck, "  [infinite]\n");
        fi;
    od;
od;

# Size of H
H_mat := Group(gensH_mats);
Print("\nSize of H: ", Size(H_mat), "\n");