FindSubgroupBasis := function(k1, k2, k3, a)
    local C, M, W, W_trans, N, N_sub, basis, i;

    # 1. Define the 9x3 coefficient matrix C
    C := [
        [ a[2][1], a[3][1], 0 ],
        [ a[2][2], a[3][2], 0 ],
        [ a[2][3], a[3][3], 0 ],
        [ 2^(k2-k1)*a[1][1], 0, -a[3][1] ],
        [ 2^(k2-k1)*a[1][2], 0, -a[3][2] ],
        [ 2^(k2-k1)*a[1][3], 0, -a[3][3] ],
        [ 0, 2^(k3-k1)*a[1][1], 2^(k3-k2)*a[2][1] ],
        [ 0, 2^(k3-k1)*a[1][2], 2^(k3-k2)*a[2][2] ],
        [ 0, 2^(k3-k1)*a[1][3], 2^(k3-k2)*a[2][3] ]
    ];

    # 2. Define the 9x9 diagonal modulo matrix M
    M := DiagonalMat([
        2^k1, 2^k1, 2^k1,
        2^k1, 2^k2, 2^k2,
        2^k1, 2^k2, 2^k3
    ]);

    # 3. Construct the 9x12 block matrix W = (C | M)
    W := [];
    for i in [1..9] do
        Add(W, Concatenation(C[i], M[i]));
    od;

    # 4. Find the right nullspace of W 
    # (which is the left nullspace of W transposed)
    W_trans := TransposedMat(W);
    N := NullspaceIntMat(W_trans);

    # 5. Extract the first 3 columns corresponding to [b12, t, b23]
    N_sub := List(N, row -> row{[1..3]});

    # 6. Find a clean Z-basis for the subgroup generated by these rows
    basis := BaseIntMat(N_sub);

    return basis;
end;

# Execute only if variables are provided externally
if IsBound(k1) and IsBound(k2) and IsBound(k3) and IsBound(a) then
    my_basis := FindSubgroupBasis(k1, k2, k3, a);
    Print(my_basis, "\n");
fi;
QUIT;