"""
Explore orbit dimension of functions under the group generated by a, b.

Transformations on binary strings (represented as lists of bits, LSB = index 0 = leftmost):
  a(0v) = 0v      -- if first bit is 0, leave unchanged
  a(1v) = 1b(v)   -- if first bit is 1, apply b to rest
  b(0v) = 1v      -- if first bit is 0, flip it to 1
  b(1v) = 0a(v)   -- if first bit is 1, flip it to 0, apply a to rest

We work with strings of fixed length n (padded with 0s at the end if needed).
Numbers 0..2^n-1 represent binary strings of length n.
"""

import numpy as np
from itertools import product


def int_to_bits(x, n):
    """Convert integer x to list of n bits, MSB first (index 0 = leftmost/first bit)."""
    return [(x >> (n - 1 - i)) & 1 for i in range(n)]


def bits_to_int(bits):
    n = len(bits)
    return sum(b << (n - 1 - i) for i, b in enumerate(bits))


def apply_a(bits):
    """Apply transformation a to a bit string (list)."""
    if len(bits) == 0:
        return bits
    if bits[0] == 0:
        return bits[:]
    else:
        return [1] + apply_b(bits[1:])


def apply_b(bits):
    """Apply transformation b to a bit string (list)."""
    if len(bits) == 0:
        return bits
    if bits[0] == 0:
        return [1] + bits[1:]
    else:
        return [0] + apply_a(bits[1:])


def build_permutations(n):
    """Build permutations of {0,...,2^n-1} for a and b."""
    N = 2 ** n
    perm_a = np.zeros(N, dtype=np.int32)
    perm_b = np.zeros(N, dtype=np.int32)
    for x in range(N):
        bits = int_to_bits(x, n)
        perm_a[x] = bits_to_int(apply_a(bits))
        perm_b[x] = bits_to_int(apply_b(bits))
    return perm_a, perm_b


def compose_perms(p1, p2):
    """Compose permutations: apply p2 first, then p1. Returns p1 ∘ p2."""
    return p1[p2]


def orbit_dimension_over_z2(f_vec, group_elements):
    """
    Compute dimension of Z/2-span of {g·f : g in group_elements}.
    f_vec: np.array of 0/1 values on {0,...,2^n-1}
    group_elements: list of permutations
    """
    N = len(f_vec)
    # Each g acts on f by: (g·f)(x) = f(g^{-1}(x))
    # Since we track permutations as perm[x] = g(x), g^{-1} is the inverse perm.
    # But for orbit dimension we just need the span of all g·f.
    # Let's collect all translates and do Gaussian elimination over Z/2.

    rows = []
    for perm in group_elements:
        # g·f: (g·f)(x) = f(g^{-1}(x))
        # perm[x] = g(x), so g^{-1}[perm[x]] = x
        # Compute inverse of perm
        inv_perm = np.argsort(perm)
        gf = f_vec[inv_perm]
        rows.append(gf.astype(np.uint8))

    return gaussian_elimination_z2(rows, N)


def gaussian_elimination_z2(rows, N):
    """Return rank of matrix over Z/2."""
    # Pack rows into integers for fast XOR
    basis = []
    for row in rows:
        # Convert to int
        v = int(''.join(map(str, row)), 2) if N <= 64 else row.tobytes()
        if N <= 128:
            v = int(''.join(map(str, row)), 2)
            for b in basis:
                v = min(v, v ^ b)
            if v:
                basis.append(v)
                basis.sort(reverse=True)
    return len(basis)


def gaussian_elim_matrix_z2(rows, N):
    """Proper Gaussian elimination over Z/2, returns rank."""
    if not rows:
        return 0
    m = len(rows)
    # Use numpy uint8 matrix
    M = np.array(rows, dtype=np.uint8)
    rank = 0
    pivot_col = 0
    for col in range(N):
        # Find pivot
        found = -1
        for row in range(rank, m):
            if M[row, col] == 1:
                found = row
                break
        if found == -1:
            continue
        # Swap
        M[[rank, found]] = M[[found, rank]]
        # Eliminate
        for row in range(m):
            if row != rank and M[row, col] == 1:
                M[row] = (M[row] + M[rank]) % 2
        rank += 1
        if rank == m:
            break
    return rank


def enumerate_group_elements(perm_a, perm_b, max_length):
    """
    Enumerate all distinct group elements as permutations for words of length <= max_length.
    Returns list of permutations.
    """
    N = len(perm_a)
    identity = np.arange(N, dtype=np.int32)

    # BFS / layer-by-layer enumeration
    # Store as dict: tuple(perm) -> True to deduplicate
    seen = {}
    current_layer = [identity]
    seen[tuple(identity)] = True
    all_elements = [identity]

    generators = [perm_a, perm_b]
    # Also include inverses: a and b might not be their own inverses
    # Let's compute inverses
    inv_a = np.argsort(perm_a).astype(np.int32)
    inv_b = np.argsort(perm_b).astype(np.int32)
    generators = [perm_a, perm_b, inv_a, inv_b]

    for length in range(1, max_length + 1):
        next_layer = []
        for elem in current_layer:
            for gen in generators:
                new_elem = compose_perms(gen, elem)  # gen ∘ elem
                key = tuple(new_elem)
                if key not in seen:
                    seen[key] = True
                    next_layer.append(new_elem)
                    all_elements.append(new_elem)
        current_layer = next_layer
        if not current_layer:
            print(f"  Group closed at length {length - 1}, size = {len(all_elements)}")
            break

    return all_elements


def compute_orbit_dim_vs_k(f_vec, perm_a, perm_b, max_k):
    """Compute orbit dimension as a function of k (word length)."""
    N = len(f_vec)
    identity = np.arange(N, dtype=np.int32)
    inv_a = np.argsort(perm_a).astype(np.int32)
    inv_b = np.argsort(perm_b).astype(np.int32)
    generators = [perm_a, perm_b, inv_a, inv_b]

    seen = {tuple(identity): identity}
    current_layer = [identity]
    all_elements = [identity]

    # Collect rows for Gaussian elim incrementally
    def get_translate(perm):
        inv_perm = np.argsort(perm)
        return f_vec[inv_perm].astype(np.uint8)

    # Matrix rows
    all_rows = [get_translate(identity)]
    dims = []

    for k in range(1, max_k + 1):
        next_layer = []
        for elem in current_layer:
            for gen in generators:
                new_elem = compose_perms(gen, elem)
                key = tuple(new_elem)
                if key not in seen:
                    seen[key] = new_elem
                    next_layer.append(new_elem)
                    all_elements.append(new_elem)
                    all_rows.append(get_translate(new_elem))
        current_layer = next_layer
        dim = gaussian_elim_matrix_z2(all_rows, N)
        dims.append((k, len(all_elements), dim))
        print(f"  k={k}: group elements so far = {len(all_elements)}, orbit dim = {dim}")
        if not current_layer:
            print(f"  Group closed at k={k}")
            break

    return dims


def main():
    n = 6  # work with strings of length n
    N = 2 ** n
    print(f"Working with binary strings of length {n}, N = {N}")

    perm_a, perm_b = build_permutations(n)

    print("Permutation a (first 16):", perm_a[:16])
    print("Permutation b (first 16):", perm_b[:16])

    # Verify: a(0v) = 0v means a fixes all strings starting with 0 (i.e., x < N/2)
    # a(1v) = 1b(v) means for x >= N/2, a(x) = N/2 + b(x - N/2)
    print("\nVerification:")
    for x in range(min(8, N)):
        bits = int_to_bits(x, n)
        print(f"  a({bits}) = {int_to_bits(perm_a[x], n)}, b({bits}) = {int_to_bits(perm_b[x], n)}")

    print("\n--- Candidate functions ---")

    # f1: first bit
    f1 = np.array([int_to_bits(x, n)[0] for x in range(N)], dtype=np.uint8)
    print(f"\nf1 = first bit:")
    dims1 = compute_orbit_dim_vs_k(f1, perm_a, perm_b, max_k=8)

    # f2: Hamming weight mod 2
    f2 = np.array([bin(x).count('1') % 2 for x in range(N)], dtype=np.uint8)
    print(f"\nf2 = Hamming weight mod 2:")
    dims2 = compute_orbit_dim_vs_k(f2, perm_a, perm_b, max_k=8)

    # f3: last bit
    f3 = np.array([x & 1 for x in range(N)], dtype=np.uint8)
    print(f"\nf3 = last bit:")
    dims3 = compute_orbit_dim_vs_k(f3, perm_a, perm_b, max_k=8)

    # f4: second bit
    f4 = np.array([int_to_bits(x, n)[1] for x in range(N)], dtype=np.uint8)
    print(f"\nf4 = second bit:")
    dims4 = compute_orbit_dim_vs_k(f4, perm_a, perm_b, max_k=8)

    # f5: x mod 4 == 0 (first two bits are 00)
    f5 = np.array([1 if int_to_bits(x, n)[:2] == [0, 0] else 0 for x in range(N)], dtype=np.uint8)
    print(f"\nf5 = indicator of strings starting with 00:")
    dims5 = compute_orbit_dim_vs_k(f5, perm_a, perm_b, max_k=8)


if __name__ == "__main__":
    main()
